### ISSUE TITLE
`refreshCache` endpoint consistency

### ISSUE THREAD

**Issue by angelicaochoa** [cBioPortal/clinical-data-dictionary#24]
Might be a good idea to make Oncotree and CDD refreshCache endpoints consistent:

CDD
https://github.com/cBioPortal/oncotree/pull/102/files#diff-979f26128c47cbdb4730b1fe4ed8f6e4R41

Oncotree
https://github.com/cBioPortal/clinical-data-dictionary/blob/master/src/main/java/org/cbioportal/cdd/web/ClinicalDataDictionaryController.java#L122

**Comment by sheridancbio** [comment]
accomplished by #25
